language: python
python:
  - "2.6"
  - "2.7"
addons:
  postgresql: "9.3"

# command to install dependencies
install:
  - "pip install -r requirements.txt"

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

# command to run tests
script: nosetests specs/test.py

# Whitelisting example
branches:
  only:
    - master
